server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # AUTH
        - id: auth
          uri: http://auth-service:8081
          predicates: [ Path=/auth/** ]

        # PROFILE
        - id: profile
          uri: http://profile-service:8083
          predicates: [ Path=/profiles/** ]

        # ENROLLMENT (specific FIRST)
        - id: enrollment-eligibility
          uri: http://enrollment-service:8084
          predicates: [ Path=/programs/*/eligibility/** ]

        - id: enrollment-enroll
          uri: http://enrollment-service:8084
          predicates: [ Path=/programs/*/enroll ]

        # Needed for agent/admin decision endpoint
        - id: enrollment-admin
          uri: http://enrollment-service:8084
          predicates: [ Path=/enrollments/** ]

        # PROGRAM CATALOG (catch-all, LAST)
        - id: program-catalog
          uri: http://program-catalog-service:8085
          predicates: [ Path=/programs/** ]

        - id: payments
          uri: http://payment-service:8086
          predicates: [ Path=/payments/** ]
app:
  jwt:
    secret: ${APP_JWT_SECRET:a6f3d8c2b7944f12a17d05c6b9f82a7d3e1f74c5a94e89b15b3f0c7e1a2d9f5c}
    publicPaths:
      - /auth/**
      - /actuator/**
      - /v3/api-docs/**
      - /swagger-ui/**
