server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: enrollment-program-actions
          uri: http://enrollment-service:8084
          predicates:
            - Path=/programs/*/eligibility/**,/programs/*/enroll,/programs/*/beneficiaries,/programs/*/beneficiaries/**
        - id: enrollment-general
          uri: http://enrollment-service:8084
          predicates:
            - Path=/enrollments/**

        - id: program-catalog
          uri: http://program-catalog-service:8085
          predicates:
            - Path=/programs/**,/cycles/**,/internal/**

        - id: profile
          uri: http://profile-service:8083
          predicates:
            - Path=/profiles/**

        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: payments
          uri: http://payment-service:8086
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
   secret: ${JWT_SECRET:${APP_JWT_SECRET:a6f3d8c2b7944f12a17d05c6b9f82a7d3e1f74c5a94e89b15b3f0c7e1a2d9f5c}}
   public-paths:
      - /auth/**
      - /actuator/**
