server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # Global CORS so Angular (http://localhost:4200) can preflight + POST JSON
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # --- AUTH (no StripPrefix; keep /auth/** intact) ---
        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        # --- ENROLLMENT (place before /programs/**) ---
        - id: enrollment-program-specific
          uri: http://enrollment-service:8084
          predicates:
            - Path=/programs/*/eligibility/**,/programs/*/enroll,/programs/*/beneficiaries/**

        - id: enrollment
          uri: http://enrollment-service:8084
          predicates:
            - Path=/enrollments/**

        # --- PROFILES ---
        - id: profiles
          uri: http://profile-service:8083
          predicates:
            - Path=/profiles/**

        # --- PROGRAM CATALOG ---
        - id: program-catalog
          uri: http://program-catalog-service:8085
          predicates:
            - Path=/programs/**,/cycles/**,/entitlements/**

        # --- PAYMENTS ---
        - id: payments
          uri: http://payment-service:8086
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

# JwtProps in your gateway expects app.jwt.publicPaths (relaxed binding accepts dash-case)
app:
  jwt:
    secret: ${JWT_SECRET:${APP_JWT_SECRET:a6f3d8c2b7944f12a17d05c6b9f82a7d3e1f74c5a94e89b15b3f0c7e1a2d9f5c}}
    public-paths:
      - /auth/**
      - /actuator/**
