spring:
  application:
    name: profile-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/profiledb}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        lob:
          non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: file:./uploads/