server:
  port: 8084
spring:
  application.name: enrollment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/enrollmentdb}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    properties.hibernate.jdbc.time_zone: UTC

management.endpoints.web.exposure.include: health,info

clients:
  programCatalogBaseUrl: ${PROGRAM_CATALOG_URL:http://program-catalog-service:8082}
  profileBaseUrl: ${PROFILE_URL:http://profile-service:8083}
